---
title: "The Scientific Foundation: What the Evidence Reveals"
---


## Retinal Imaging & Cardiovascular Health: A Deep Connection

The human eye, often regarded as a window to the soul, increasingly appears to be a sophisticated mirror reflecting the overall health of the circulatory system. Within the retina, a delicate network of blood vessels—arterioles and venules—provides a unique, non-invasive opportunity to observe systemic vascular health.  These microvessels, readily visible via non-mydriatic fundus photography, undergo subtle yet significant changes that are correlated with the increased risk of developing ischemic cardiovascular disease (ICVD). These changes, which include but are not limited to variations in arteriolar diameter, venular dilation, and the presence of microvascular damage, all indicate an underlying dysfunction within the body’s broader vascular system. In this section, we will explore the growing evidence linking retinal microvasculature and ICVD.

Traditional methods for assessing cardiovascular health, such as blood tests, blood pressure measurements, and questionnaires, provide essential but sometimes incomplete pictures of risk. These tests often require invasive procedures and/or complex interpretation and can be difficult to deploy at scale in community or primary care settings. Furthermore, risk assessment for CVD is still limited by the reliance on traditional risk factors, as many patients without these risk factors still develop heart disease.  Retinal imaging, especially when combined with advanced image analysis and artificial intelligence (AI), offers a novel, non-invasive avenue for more direct and accessible assessment of a person’s vascular health and a tool that can be readily deployed in a wide range of clinical and community settings. One of the most compelling areas of research is the development of AI-driven approaches that are capable of predicting ICVD risk from retinal images, and these have shown remarkable performance in several large population studies.

One such study published in the *Science Bulletin* \[1], details how researchers from China utilized a vast dataset of over 390,000 retinal images to train a deep-learning algorithm for ICVD risk stratification. This study was based on non-mydriatic fundus images which makes them easy to collect in most clinical environments. The algorithm was designed to estimate a patient's 10-year risk of ICVD events by learning to identify patterns in fundus images that may not be apparent to the naked eye, such as subtle changes in microvasculature. The model performed exceptionally well in both internal and external validation datasets, demonstrating robustness and generalizability across different groups of people. The model achieved an impressive adjusted R² of 0.876 on an internal data set and 0.638 on the external validation set which is the Beijing Research on Ageing and Vessel (BRAVE) data set.   The adjusted R2 represents the proportion of variability that could be explained with this model.  An R2 of 1 suggests that the model perfectly predicts outcomes with no variance, while 0 represents a model with no power to predict outcomes. These results show that AI-driven assessment of retinal imaging has high potential to estimate ICVD risk. 

Furthermore, when using the trained algorithm to classify the risk of ICVD, the model showed a very high area under the receiver operating characteristic (AUC) curve for detecting patients with a 10-year ICVD risk of ≥5%.  The AUC was 0.971 (95% CI: 0.967-0.975) in the internal validation dataset and 0.859 (95% CI: 0.822-0.895) in external validation. For the higher threshold of ICVD risk (≥ 7.5%), the AUC was 0.976 (95% CI: 0.973-0.980) for the internal validation dataset, and 0.876 (95% CI: 0.816-0.937) for external data. An AUC value close to 1 indicates perfect diagnostic accuracy. These AUC values demonstrate the high predictive power of this algorithm, which is consistent with other studies that have also seen a high predictive power of AI algorithms based on fundus images.   The results indicate that this algorithm may be a feasible and accurate alternative to established methods for assessing risk of ICVD, which may lead to wide scale implementation of retinal imaging in routine check-ups. The findings also show that AI algorithms are able to learn the association of microvascular changes with ICVD, including venular dilatation and arteriolar narrowing. AI can extract subtle relationships from images which, while difficult to appreciate with the naked eye, can be predictive of health outcomes.  These subtle changes are also consistent with other traditional risk factors, like blood pressure. 

The study's authors noted a few limitations. First, the data was collected cross-sectionally, and their outcomes were predicted from an estimation tool that used traditional risk factors, rather than actual longitudinal ICVD event data. To confirm the prediction ability, a follow-up study of the BRAVE data is planned. Second, smoking status was absent in the dataset. Despite the limitations, the findings still provide compelling evidence of AI's potential in ICVD risk assessment using retinal images, given the simplicity of the approach and the high degree of predictive power.

## Retinal Imaging & Cerebral Health: A Reflection of the Brain

The retina, during development, is an embryological extension of the brain, and as such shares an intimate physiological and anatomical relationship with it [15]. It's an unusual tissue in that it can be observed non-invasively and allows an easy way to examine microvascular function. It is because of this that scientists are exploring the potential role of retinal imaging in understanding cerebrovascular and neurodegenerative diseases such as dementia. Retinal images provide a novel way to monitor cerebral health.

A growing body of research has established correlations between changes in the retinal vasculature and an increased risk of dementia. Studies have revealed that individuals with retinal microvascular abnormalities—including arteriolar narrowing, venular dilation, and the presence of retinopathy—have a higher likelihood of developing cognitive decline and dementia \[9-11].  This link is rooted in the similarities between retinal and cerebral microvasculature. Both vascular systems share analogous structures and physiological functions, and changes in one may reflect similar pathological changes in the other. The implication of this relationship is important, because cerebrovascular disease is known to be a major contributor to dementia. Instead of solely relying on traditional cognitive tests, retinal imaging could be employed for population-wide screening, identifying high-risk patients earlier and allowing for earlier interventions.

In one innovative study, researchers developed a novel algorithm utilizing fundus photographs to estimate the Cardiovascular Risk Factors, Aging, and Incidence of Dementia (CAIDE) dementia risk score. The CAIDE is a well-established tool that uses a multidimensional risk factors (age, sex, educational level, physical inactivity, systolic blood pressure, total cholesterol, and body mass index) to predict the 20-year risk of dementia. The study showed that the algorithm had a high adjusted R2 (0.80 in internal validation and 0.58 in external validation) for predicted CAIDE risk score compared with the actual score, suggesting the algorithm was able to extract the relevant data in the retinal photos.   Furthermore, the external validation of the algorithm revealed a high area under the receiver operating characteristic curve (AUC) of 0.926 (95% CI: 0.913–0.939), indicating strong ability to discriminate individuals with high dementia risk.  This predictive ability is very impressive, as CAIDE scores have also shown to be predictive in a large multiethnic population.18-20 This study moves beyond simple correlation and demonstrates that AI-driven analysis of retinal images can predict complex metrics associated with dementia risk, indicating a path for non-invasive early detection and risk stratification.

Further supporting this connection between the retina and brain is work examining the impact of environmental factors on retinal structures. In a study, researchers at the University College London analyzed the UK Biobank data set, and determined that exposure to ambient air pollution may be linked to changes in retinal layer thicknesses [17]. They found that increased exposure to fine particulate matter (PM2.5) and nitrogen oxides were correlated with a thicker retinal nerve fiber layer (RNFL) and a thinner ganglion cell-inner plexiform layer (GCIPL). Moreover, higher levels of PM2.5 absorbance were associated with a thinner RNFL, inner nuclear layer, and OPL+ONL.  These findings not only suggest the impact of environmental toxins on retinal structure, but imply that these same toxins might also cause similar changes in other areas, including the brain.  Taken together, these investigations suggest that AI-based analysis of retinal images can potentially provide early, non-invasive indicators of brain health, providing a window into the pathological processes that may precede neurodegenerative conditions such as dementia. 

## Retinal Imaging & Anemia: Visualizing Blood Composition

Beyond its role as a window into vascular and neurological health, the retina also offers a unique opportunity for non-invasive assessment of hematological conditions such as anemia. Anemia, characterized by a deficiency in red blood cells or hemoglobin, affects an estimated 1.6 billion individuals worldwide and presents significant challenges in its diagnosis and management [1,2]. Due to the invasiveness and cost of diagnostic tests that require blood samples, the condition is often left undiagnosed, particularly in resource limited settings.  However, the recent advances in AI, particularly when applied to retinal fundus photographs, offer a promising alternative for non-invasive detection and management of this important condition [18].

Researchers have demonstrated that AI algorithms can accurately quantify hemoglobin (Hb) levels and detect the presence of anemia using fundus photos alone.  In a large-scale study published in *Nature Biomedical Engineering*, a team of scientists used fundus images from the UK Biobank to develop deep learning models for the detection of anaemia using fundus photos, participant metadata or a combination of both [18]. They found that a combined model of fundus images with metadata was most accurate, and the study used a validation set of 11,388 study participants. The results of the combined model showed a mean absolute error (MAE) of 0.63 g/dL (95% CI, 0.62–0.64) in predicted Hb concentration, an AUC of 0.88 (95% CI, 0.86-0.89) for anaemia detection, an area under the ROC curve of 0.88 (95% confidence interval (CI) 0.86-0.89) for detection of any anemia, and an area under the ROC curve of 0.95 (95% CI, 0.93-0.97) for moderate to severe anemia.  The MAE of 0.63 g/dl was close to the accuracy of laboratory measurements of 0.14 g/dl (ref) and much more accurate than non-invasive point-of-care devices, whose accuracy is 1.1 to 1.2 g/dl.  These results are striking because these outcomes are based entirely on non-invasive measurements.  The fundus photos capture the subtle changes associated with low haemoglobin, including pallor of the retina and venous tortuosity. These findings not only highlight the capabilities of deep learning in processing complex image data but also show a clear path for a non-invasive method of diagnosing anaemia.
   
Moreover, the study also found that that the algorithm could detect anaemia in a group of 539 participants with self-reported diabetes, with comparable performance.  The study had a slightly larger MAE of 0.73 g/dl (95% CI, 0.68-0.78 g/dl) and an AUC of 0.89 (95% CI, 0.85-0.93), as compared to all participants in the study. These results are particularly relevant because anemia is frequently associated with diabetes (up to 23% of patients with diabetes remain undiagnosed for anaemia) and is shown to increase morbidity and mortality in these populations. Given the potential for regular retinal screening of diabetic retinopathy, the capability of AI to also detect anemia from retinal photos can be of immense use and provide additional opportunities for healthcare screening. 


## Retinal Imaging for Prediction of Age and Mortality Risk

While conventional wisdom might associate the retina solely with visual function, research is increasingly demonstrating that the eye also offers a window into the ageing process and a way to quantify mortality risk. The retina, composed of neural tissue and blood vessels, reflects both local changes that are influenced by age as well as the wider systemic effects of aging on the human body. Researchers have found that subtle age-related changes to the retina can be identified through fundus photography and quantified using AI, creating a novel biomarker of biological age and its connection with mortality risk.

A team of researchers in Singapore developed an algorithm that can estimate a patient’s biological age, termed RetiAGE, based on deep learning from fundus images^[@zhu_retinal_2023].   The algorithm was initially trained on fundus photographs from 40,480 Korean adults and then evaluated using 56,301 participants of the UK Biobank, which demonstrated its generalizability across diverse populations and ethnicities. They found that, using a cut off of being equal or greater than 65 years of age, the algorithm showed an AUC of 0.76, with an AUPRC of 0.399.  More importantly, they then stratified participants by their RetiAGE and followed them for over 10 years and found that individuals in the fourth quartile of RetiAGE had a 67% increased risk of all-cause mortality, 142% increased risk of CVD-related mortality, and 60% increased risk of cancer related mortality compared to those in the lowest quartile. Critically, these associations were independent of chronological age and of a number of established ageing biomarkers including albumin, creatinine, glucose and C-reactive protein. This data suggests the algorithm is capturing some of the biological changes associated with aging that conventional biomarkers do not identify. In this study, the researchers also showed that the addition of RetiAGE increased the ability to predict mortality risk beyond the conventional risk factors.

Similarly, another study based on a 10 year longitudinal analysis of fundus images from the UK Biobank found that the retinal age gap (difference between predicted and chronological age) was associated with a 2% increase in all-cause mortality risk and 3% increased risk of non-CVD/non-cancer mortality [19].  While they did not find a significant association between retinal age gap and CVD or cancer-related mortalities, their findings underscore a role of retinal changes in broader ageing processes.  Both the above studies have strong statistical significance with large populations and rigorous methodology, thus supporting the hypothesis that retinal fundus imaging could offer a non-invasive means of determining both biological age and risk of mortality.
   
While the biological mechanisms underlying the observed retinal changes associated with age and mortality remain the subject of future study, it is becoming increasingly evident that AI-driven analysis of retinal images can provide novel markers of both biological ageing and long-term health outcomes, demonstrating significant potential as a tool to assess mortality risk in a range of different settings.

## A Growing Body of Evidence: Beyond The Main Focus

The body of evidence supporting the use of fundus photography for general health assessment continues to grow, expanding beyond cardiovascular, neurological, and hematological conditions.  AI is proving to be a versatile tool, and its capabilities in analyzing the complexity of retinal images are expanding our understanding of the retina and its link to a range of systemic diseases.

For example, diabetic retinopathy can be detected with high accuracy with the use of AI-based retinal imaging in clinical settings. A study published in *Ophthalmology* showed that deep learning systems could achieve excellent sensitivity and specificity, comparable to human experts for diabetic retinopathy detection [20], a common microvascular complication of diabetes.  AI and retinal imaging is rapidly transforming diabetic retinopathy management, enabling scalable screening and early detection for disease prevention.  The AI systems have also been used to help predict the progression of the retinopathy, which could allow clinicians to improve treatment strategies.

Glaucoma, another common ocular disease linked with various systemic factors, can also be identified by AI algorithms applied to fundus photos [21,22]. These findings may have clinical impact because glaucoma is a frequent cause of blindness and can potentially be screened and treated earlier. Beyond this, some researchers have explored the link between thyroid disease and retinal fundus images and have found promising applications for diagnostic purposes, though further work is required.

Future work in the field will no doubt bring further discovery and refinement of these techniques.  Further research may uncover a spectrum of new correlations between subtle retinal features and various systemic conditions. The ongoing convergence of high-resolution imaging, big data analytics, and AI offers an exciting prospect for unlocking even more information about the human body from a simple, non-invasive retinal photograph.

