project:
  type: book
  output-dir: docs


book:
  title: "Eyes on Health"
  author: "Richard Sprague"
  search: true
  page-footer: "Copyright 2025 Opticare, Inc"
  site-url: https://opticareai.github.io/eyes-on-health/
  downloads: [pdf, epub]
  date: "1/5/2025"
  cover-image: _resources/book/Eyes-Kindle_Book_Cover_6x9-Medium.jpeg
  chapters:
    - index.qmd
    - 1-Chapter-Intro.qmd
    - 2-Chapter-Science.qmd
    - 3-Chapter-Wellness.qmd
    - 4-Chapter-Practical.qmd
    - 5-Chapter-Guidebook.qmd
    - 6-Chapter-Faster.qmd
    - 7-Chapter-Future.qmd
    - 8-Chapter-Beyond.qmd
    - 9-Chapter-Skepticism.qmd
    - 10-Chapter-Final.qmd
    - summary.qmd
    - references.qmd

bibliography: _resources/book/Eyecare.bib 



format:
  html:
    theme: minty
    css: _resources/book/css/normalize.css
    standalone: true
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    papersize: "Letter"
    mainfont: "Georgia"
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    standalone: true

  epub:
    cover-image: _resources/book/Eyes-Kindle_Book_Cover_6x9.png
  