project:
  type: book
  output-dir: docs


book:
  title: "Eyes on Health"
  author: "Richard Sprague"
  search: true
  page-footer: "Copyright 2025 Opticare, Inc"
  site-url: https://opticareai.github.io/eyes-on-health/
  downloads: [pdf, epub]
  date: "3/19/2025"
  cover-image: _resources/book/eyeshealthcover2.png
  

bibliography: _resources/book/Eyecare.bib
nocite: '@*'


format:
  html:
    theme: minty
    css: _resources/book/css/normalize.css
    standalone: true
    toc: true
    link-external-newwindow: true
  pdf:
    papersize: "Letter"
    mainfont: "Georgia"
    toc: true
    documentclass: scrbook
    geometry: paperwidth=6in,paperheight=9in
    standalone: true
    toc-depth: 2  
    keep-tex: true
    header-includes:
      - \raggedbottom


  epub:
    cover-image: _resources/book/eyeshealthcover2.png
  